-- Adiciona a coluna de margem de lucro ao pedido de venda.
--
-- A margem é OPCIONAL: aplicada apenas na criação/edição direta do
-- pedido, embutida item a item no unitPrice pelo SalesOrderMapper.
-- Pedidos convertidos de proposta (createFromQuotation) e pedidos
-- antigos ficam com profit_margin NULL — a margem da proposta já vem
-- embutida no snapshot dos preços.
--
-- DECIMAL(5,2): até 999.99% (mesma precisão de quotations e
-- technical_proposals).
ALTER TABLE sales_orders ADD COLUMN profit_margin DECIMAL(5,2) NULL;